#!/usr/bin/env node
/**
 * PreToolUse Hook: Research Pipeline Anti-Fabrication Guard
 *
 * Event: PreToolUse (runs before Bash/Write/Edit)
 * Purpose: Mechanically prevent experiment-runner from writing to results files.
 *
 * This is CODE-LEVEL enforcement, not prompt-level — the LLM physically cannot
 * modify results.json or sanity-check.json inside .research/ directories.
 * These files must only be written by training/validation scripts.
 *
 * Also protects state.json from accidental corruption by workers.
 */

const path = require('path');
const fs = require('fs');

// Read stdin input
let input = {};
try {
  const stdinData = fs.readFileSync(0, 'utf8');
  if (stdinData.trim()) {
    input = JSON.parse(stdinData);
  }
} catch {
  // Use default empty object
}

const toolName = input.tool_name || '';
const cwd = input.cwd || process.cwd();

let decision = 'allow';
let reason = '';

// === Anti-fabrication: protect results files ===
if (toolName === 'Write' || toolName === 'Edit') {
  const filePath = input.tool_input?.file_path || '';
  const resolved = path.resolve(cwd, filePath);

  // Check if file is inside .research/ directory
  if (resolved.includes('.research/') || resolved.includes('.research\\')) {
    const basename = path.basename(resolved);

    // Tier 1: DENY — results files are write-protected
    const protectedFiles = [
      'results.json',
      'sanity-check.json',
    ];

    if (protectedFiles.includes(basename)) {
      decision = 'deny';
      reason = `Results file "${basename}" is write-protected (anti-fabrication constraint). ` +
               'This file must only be generated by training/validation scripts, not by LLM.';
    }

    // Tier 2: WARN — state.json should only be modified via StateManager
    if (basename === 'state.json') {
      // Allow but add system message warning
      const result = {
        continue: true,
        systemMessage: '⚠️ Modifying state.json directly. Prefer using StateManager (research_utils.py) ' +
                       'for consistent state updates with schema validation.'
      };
      console.log(JSON.stringify(result));
      process.exit(0);
    }
  }
}

// === Bash command protection ===
if (toolName === 'Bash') {
  const command = input.tool_input?.command || '';

  // Prevent redirecting output to protected result files
  // Patterns match paths ending in exactly /results.json or /sanity-check.json
  const dangerousPatterns = [
    // Redirect to results.json (exact basename after / or at start)
    />\s*\S*\/results\.json/,
    />\s*\S*\/sanity-check\.json/,
    // tee to results files
    /tee\s+\S*\/results\.json/,
    /tee\s+\S*\/sanity-check\.json/,
    // cp/mv to results files
    /(?:cp|mv)\s+.*\s+\S*\/results\.json/,
    /(?:cp|mv)\s+.*\s+\S*\/sanity-check\.json/,
  ];

  // Only check within .research context
  if (command.includes('.research') || command.includes('phase')) {
    for (const pattern of dangerousPatterns) {
      if (pattern.test(command)) {
        decision = 'deny';
        reason = 'Writing to results/sanity-check files via shell is not allowed (anti-fabrication constraint). ' +
                 'These files must only be generated by training/validation scripts.';
        break;
      }
    }
  }
}

// === Build output ===
if (decision === 'deny') {
  const errorOutput = {
    hookSpecificOutput: { permissionDecision: 'deny' },
    systemMessage: `🛑 Anti-Fabrication Guard: ${reason}\n\n` +
      'Results files are mechanically write-protected. Only training scripts may generate them.\n' +
      'If you need to report experiment status, update state.json or reasoning.md instead.'
  };
  console.error(JSON.stringify(errorOutput));
  process.exit(2);
} else {
  console.log(JSON.stringify({ continue: true }));
  process.exit(0);
}
